version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Build image
          command: docker build -t react-skeleton:$CIRCLE_SHA1 .

      - run:
          name: Add GitHub packages read/write token
          command: echo "$GITHUB_PACKAGES_READ_WRITE_TOKEN" > ~/.github-packages-read-write-token

      - run:
          name: Log into GitHub
          command: cat ~/.github-packages-read-write-token | docker login docker.pkg.github.com -u RickBorst --password-stdin

      - run:
        name: Push image to GitHub
        command: docker push docker.pkg.github.com/rickborst/react-skeleton/react-skeleton:$CIRCLE_SHA1
